games:
  hypixel:
    type: minecraft
    host: mc.hypixel.net
    metrics:
      protocol:
        description: 'Minecraft Protocol'
        type: 'gauge'
        value: raw.vanilla.raw.version.protocol
        labels:
          connect: raw.connect
          otherMetric: (data) => data.version.toUpper()
