games:
  hypixel:
    type: minecraft
    host: mc.hypixel.net
    metrics:
      connect:
        type: 'gauge'
        description: 'Metric Connect'
        value: raw.vanilla.raw.version.protocol
        labels:
          label1: raw.vanilla.connect
          label2: (data) => data.version
